### ISSUE TITLE
integration with non typical setup

### ISSUE THREAD

**Issue by basz** [proophsoftware/prooph-cli#11]
doesn’t play nice with expressive setups that are a bit of it's recommended or skeleton setup. Is there room for improvement.

I use a non standard glob pattern and use a config/config.php file that looks like this one:

```
defined('APP_ENV') || define('APP_ENV', getenv('APP_ENV'));

if (APP_ENV === false) {
    die("Define 'APP_ENV' as environment variable!" . PHP_EOL);
}

$globPattern = sprintf('config/autoload/{,*.}{global,global.secrets,%s,%s.secrets,local}.php', APP_ENV, APP_ENV);

$configManager = new ConfigManager([
    new PhpFileProvider($globPattern),
], 'data/cache/config.php');
```

Not sure what a good fix is for vendor-to-top-application configuration. simply including the config and dependancies would work i guess.

Also, this is an interesting pattern, which might inspire some of you :-P

https://github.com/zf-fr/zfr-oauth2-server/blob/master/src/ModuleConfig.php

which allows usage as follows;

```
$configManager = new ConfigManager([
    new \ZfrOAuth2\Server\ModuleConfig(),
    new PhpFileProvider($globPattern),
], 'data/cache/config.php');
```

**Comment by codeliner** [comment]
ping @sandrokeil

**Comment by sandrokeil** [comment]
@basz I'm not sure how to solve this. `prooph-cli` works independent of the application, for instance Zend Expressive. The module class does not solve the problem, because an own Service Manager is used. Or I'm wrong? Another solution is to create an [own cli file](https://github.com/proophsoftware/prooph-cli/blob/master/bin/prooph-cli) with another configuration.

Maybe we should remove the config file, I think it's not useful anymore.

**Comment by basz** [comment]
hi! if prooph-cli should work independently of the application (great!) it then should not try to read the autoload directory of the application. If it needs access to application configuration I guess it should use the result of the config/config.php file. Same goes for the used container.

Not sure what you mean by 'an own'...

**Comment by sandrokeil** [comment]
@basz You're right. I will remove it, because it's not needed anymore. We use environment variables to configure things like class namespace.

**Comment by basz** [comment]
figured so much. works great by the way! I started to implement the namespace prefix as command argument until I found the environment variable... (the env don't advertise themselves through the help command)

**Comment by sandrokeil** [comment]
Good point. This is missing in the docs and in the command help. I will fix it.

**Comment by basz** [comment]
If you place a setter on the PSR4 helper, you could insert the namespace from a command line arg

**Comment by sandrokeil** [comment]
This could be useful too. :+1:

**Comment by sandrokeil** [comment]
@basz Please take a look at #16. This resolves your issues. The namespace via command line argument is difficult, because of the order of optional arguments.

**Comment by basz** [comment]
Isn't order of cli args free if you use '--argument=value'?

**Comment by sandrokeil** [comment]
Closing this because of #14 and #16
