### ISSUE TITLE
Retrieve class info console helper via service manager 

### ISSUE THREAD

**Issue by sandrokeil** [proophsoftware/prooph-cli#4]
The default class info console helper is the `Psr4Info` helper which can be [configured via environment variables](https://github.com/proophsoftware/prooph-cli/blob/master/bin/prooph-cli#L67), but it would be nice to override them in the service container to allow users to create your own class info console helper.
- [ ] Create a factory for Psr4Info console helper with current behaviour
- [ ] Retrieve Psr4Info console helper via service manager
- [ ] Check [overriding via config](https://github.com/proophsoftware/prooph-cli/blob/master/config/config.php#L20)

**Comment by codeliner** [comment]
@sandrokeil Can we close this?

**Comment by sandrokeil** [comment]
Yes
